services:
  web:
    build: .
    container_name: careerai_web
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://db:27017/
      - MONGO_DB_NAME=careerai-db
      - DOCKER_ENV=true
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: careerai_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
